name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      # =====================================================
      # CHECKOUT
      # =====================================================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # =====================================================
      # AWS AUTHENTICATION
      # =====================================================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # =====================================================
      # TERRAFORM SETUP
      # =====================================================

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # =====================================================
      # TERRAFORM DESTROY
      # =====================================================

      - name: Terraform Destroy
        run: |
          terraform destroy \
          -auto-approve \
          -var="public_key=${{ secrets.VM_PUBLIC_KEY }}"
